#!/bin/zsh

# Smart directory navigation for monorepo packages
# Usage: nav [partial_directory_name] | nav r (for root) | nav --set/-s [search] | nav --show

# Get path to nav config file
function _nav_get_config_path() {
    echo "$HOME/.config/zsh/nav.conf"
}

# Read monorepo root with priority: Superset env var > config file > default
function _nav_read_config() {
    # Priority 1: Superset workspace env var (when running in Superset terminal)
    if [[ -n "$SUPERSET_WORKSPACE_PATH" ]]; then
        echo "$SUPERSET_WORKSPACE_PATH"
        return
    fi

    # Priority 2: Config file
    local config_file="$(_nav_get_config_path)"
    if [[ -f "$config_file" ]]; then
        source "$config_file"
        echo "$MONOREPO_ROOT"
        return
    fi

    # Priority 3: Default fallback
    echo "$HOME/code/monorepo"
}

# Write new monorepo root to config
function _nav_write_config() {
    local new_root="$1"
    local config_file="$(_nav_get_config_path)"
    local config_dir="$(dirname "$config_file")"

    # Create config directory if it doesn't exist
    mkdir -p "$config_dir"

    # Write config
    cat > "$config_file" << EOF
# Navigation script configuration
# Generated by nav --set on $(date)
MONOREPO_ROOT=$new_root
EOF

    echo "Config updated: $config_file"
}

# Interactive repository selection
function _nav_set_repo() {
    local search_term="$1"

    # Find git repos and directories with package.json
    local repos=$(find "$HOME/code" -maxdepth 2 \
        \( -type d -name ".git" -exec dirname {} \; \
        -o -name "package.json" -type f -exec dirname {} \; \) \
        2>/dev/null | sort -u)

    if [[ -z "$repos" ]]; then
        echo "No repositories found in ~/code"
        return 1
    fi

    local selected_repo

    # Filter repos if search term provided
    if [[ -n "$search_term" ]]; then
        local filtered_repos=$(echo "$repos" | grep -i "$search_term")

        if [[ -z "$filtered_repos" ]]; then
            echo "No repositories found matching: $search_term"
            return 1
        fi

        local match_count=$(echo "$filtered_repos" | wc -l | tr -d ' ')

        if [[ "$match_count" -eq 1 ]]; then
            # Single match - select directly
            selected_repo="$filtered_repos"
        else
            # Multiple matches - use fzf with search term as query
            if ! command -v fzf >/dev/null 2>&1; then
                echo "Multiple matches found. Install fzf for interactive selection, or be more specific:"
                echo "$filtered_repos"
                return 1
            fi

            selected_repo=$(echo "$filtered_repos" | fzf \
                --height=40% \
                --reverse \
                --query="$search_term" \
                --prompt="Select target repository: " \
                --preview='ls -la {} | head -20' \
                --preview-window=right:50%)
        fi
    else
        # No search term - show all with fzf
        if ! command -v fzf >/dev/null 2>&1; then
            echo "fzf is required for interactive selection. Please install fzf or provide a search term."
            return 1
        fi

        selected_repo=$(echo "$repos" | fzf \
            --height=40% \
            --reverse \
            --prompt="Select target repository: " \
            --preview='ls -la {} | head -20' \
            --preview-window=right:50%)
    fi

    if [[ -z "$selected_repo" ]]; then
        echo "No repository selected."
        return 1
    fi

    # Validate selection
    if [[ ! -d "$selected_repo" ]]; then
        echo "Error: Selected path is not a valid directory: $selected_repo"
        return 1
    fi

    # Write to config (silently)
    _nav_write_config "$selected_repo" > /dev/null

    echo "Set target repository: $selected_repo"

    # Navigate to the repository root
    cd "$selected_repo"
    echo "Navigated to: $(pwd)"

    return 0
}

function nav() {
    # Handle --set/-s flag for repository selection
    if [[ "$1" == "--set" || "$1" == "-s" ]]; then
        _nav_set_repo "$2"
        return $?
    fi

    # Handle --show flag to display current config
    if [[ "$1" == "--show" ]]; then
        local current_root="$(_nav_read_config)"
        local source_info
        if [[ -n "$SUPERSET_WORKSPACE_PATH" ]]; then
            source_info="from Superset workspace"
        elif [[ -f "$(_nav_get_config_path)" ]]; then
            source_info="from config"
        else
            source_info="default"
        fi
        echo "Current target repository: $current_root ($source_info)"
        return 0
    fi
    local search_term="$1"
    local monorepo_root
    local matching_dirs
    local selected_dir

    # Read monorepo root from config
    monorepo_root="$(_nav_read_config)"
    if [[ ! -d "$monorepo_root" ]]; then
        echo "Error: Repository directory not found at $monorepo_root"
        echo ""
        echo "Run 'nav --set' to configure a different repository."
        return 1
    fi

    # Handle root navigation
    if [[ "$search_term" == "r" ]]; then
        cd "$monorepo_root"
        echo "Navigated to monorepo root: $(pwd)"
        return 0
    fi

    # Find all directories with package.json, limiting search depth and excluding cache directories
    # Most monorepos have packages within 3-4 levels, so -maxdepth 5 should be sufficient
    matching_dirs=$(find "$monorepo_root" -maxdepth 3 -name "package.json" -type f \
        -not -path "*/node_modules/*" \
        -not -path "*/.next/*" \
        -not -path "*/dist/*" \
        -not -path "*/build/*" \
        -not -path "*/.cache/*" \
        -not -path "*/coverage/*" \
        -not -path "*/.nyc_output/*" \
        -exec dirname {} \; | sort)

    if [[ -z "$matching_dirs" ]]; then
        echo "No directories with package.json found in the monorepo."
        return 1
    fi

    # Convert absolute paths to relative paths for display and matching
    local relative_dirs=$(echo "$matching_dirs" | sed 's|'"$monorepo_root"'/||g')

    # If no search term provided, show all options with fzf
    if [[ -z "$search_term" ]]; then
        if command -v fzf >/dev/null 2>&1; then
            local selected_relative=$(echo "$relative_dirs" | fzf --height=40% --reverse --prompt="Select directory: ")
            if [[ -n "$selected_relative" ]]; then
                selected_dir="$monorepo_root/$selected_relative"
            fi
        else
            echo "Available directories:"
            echo "$relative_dirs" | nl
            echo
            echo "Please provide a search term or install fzf for interactive selection."
            return 1
        fi
    else
        # Filter directories based on search term (case-insensitive) using relative paths
        local filtered_relative=$(echo "$relative_dirs" | grep -i "$search_term")

        if [[ -z "$filtered_relative" ]]; then
            echo "No directories found matching: $search_term"
            return 1
        fi

        local match_count=$(echo "$filtered_relative" | wc -l | tr -d ' ')

        if [[ "$match_count" -eq 1 ]]; then
            # Single match - navigate directly
            selected_dir="$monorepo_root/$filtered_relative"
        else
            # Multiple matches - use fuzzy finder if available
            if command -v fzf >/dev/null 2>&1; then
                local selected_relative=$(echo "$filtered_relative" | fzf --height=40% --reverse --prompt="Select directory: " --query="$search_term")
                if [[ -n "$selected_relative" ]]; then
                    selected_dir="$monorepo_root/$selected_relative"
                fi
            else
                echo "Multiple matches found for '$search_term':"
                echo "$filtered_relative" | nl
                echo
                echo "Please be more specific or install fzf for interactive selection."
                return 1
            fi
        fi
    fi

    # Navigate to selected directory
    if [[ -n "$selected_dir" ]]; then
        cd "$selected_dir"
        echo "Navigated to: $(echo "$selected_dir" | sed 's|'"$monorepo_root"'/||g')"

        # Show some useful info about the package
        if [[ -f "package.json" ]]; then
            local package_name=$(grep -o '"name"[[:space:]]*:[[:space:]]*"[^"]*"' package.json | cut -d'"' -f4)
            if [[ -n "$package_name" ]]; then
                echo "Package: $package_name"
            fi
        fi
    fi
}

# Completion function for the nav command
function _nav_completion() {
    # Read monorepo root from config
    local monorepo_root="$(_nav_read_config)"
    local dirs

    if [[ ! -d "$monorepo_root" ]]; then
        return 1
    fi

    # Get directory names (relative to monorepo root) for completion
    dirs=$(find "$monorepo_root" -maxdepth 5 -name "package.json" -type f \
        -not -path "*/node_modules/*" \
        -not -path "*/.next/*" \
        -not -path "*/dist/*" \
        -not -path "*/build/*" \
        -not -path "*/.cache/*" \
        -not -path "*/coverage/*" \
        -not -path "*/.nyc_output/*" \
        -exec dirname {} \; | sed 's|'"$monorepo_root"'/||g' | sed 's|^./||g' | sort)

    # Generate completions based on directory names
    local -a suggestions
    suggestions+=("r")  # Add root option
    while IFS= read -r dir; do
        suggestions+=("$dir")
        # Also add just the basename for easier completion
        suggestions+=("$(basename "$dir")")
    done <<< "$dirs"

    # Remove duplicates and provide completions
    printf '%s\n' "${suggestions[@]}" | sort -u
}

# Set up completion
compdef _nav_completion nav

# Optional: Add an alias for even shorter usage
alias gt='nav'
